name: Zhaoyue Sun
theme: minima
minima:
  header_pages:
    - index.md
    - blogs/blogs.md
# url: https://zhaoyuesun.github.io
# disqus:
#     shortname: zhaoyuesun-github-io
utterances:
  repo: "ZhaoyueSun/homepage"
  issue-term: "pathname"
  label: "Comment"
  theme: "github-light"

